### ISSUE TITLE
Bug - Intermittent recovery test failure - should recover before bls key update

### ISSUE THREAD

**Issue by JohnGuilding** [getwax/bls-wallet#434]
An intermittent issue has been noticed in the `./contracts` tests when running them via github workflows. The tests can be made to pass by running the workflow again.

It is an assertion error with a recovery test called `should recover before bls key update`:

```
1) Recovery
       should recover before bls key update:

      AssertionError: expected [ …(4) ] to deeply equal [ …(4) ]
      + expected - actual

       [
         "0x1aa403127efdaa248c48129e79456ea1376e23148cffa67a3d2cd3b40ff258a0"
      -  "0xf2de0cf24049b35e534ee86d8453879f263793c755c7d60af1bd36836bd50d"
      +  "0x00f2de0cf24049b35e534ee86d8453879f263793c755c7d60af1bd36836bd50d"
         "0x23a96ae8c56c636b4e838c5bb2119c67fefa337d1c041a5fee406f0e2303a0fa"
         "0x0fb017c95b9816cdb62b277ac0f5d850c2d14d04450e7db9a1a80a16eff9d4d1"
       ]
```

First failure: https://github.com/web3well/bls-wallet/actions/runs/3831775318/jobs/6521308233
Second failure: https://github.com/web3well/bls-wallet/actions/runs/3837441994/attempts/1

**Comment by jacque006** [comment]
Encountered a similar but different test failure in one of my CI runs on https://github.com/web3well/bls-wallet/pull/366

![Screenshot from 2023-01-04 13-31-24](https://user-images.githubusercontent.com/10394161/210645081-b4633df4-7086-4ed8-898e-7f29e0223646.png)

Re-run passed.

**Comment by JohnGuilding** [comment]
Encountered again https://github.com/web3well/bls-wallet/actions/runs/3952434274/jobs/6767504581

Re-run passed

**Comment by JohnGuilding** [comment]
Observed locally. Re-run passes

![Image](https://user-images.githubusercontent.com/54913924/214025920-f7a2f509-23aa-42a5-bff8-89446549f855.png)

**Comment by jacque006** [comment]
### Root Cause

When `BigNumber.from` parses a hex string as input, it strips pairs of leading zeroes (i.e. empty/padding 2 nibbles or 1 byte). This makes sense as a hexadecimal value with padding zeros is the same as one without:

`parseInt("0x01", 16) === parseInt("0x0001", 16) === 1 // true`

The underlying BLS client library we use returns hex values as strings, such as [BLS public keys](https://github.com/thehubbleproject/hubble-bls/blob/master/src/mcl.ts#L24) which includes padding/leading zeros.

When these values are output again as strings via `BigNumber.toHexString`, those pairs of zeroes as front padding no longer exist because from the `BigNumber`'s point of view, they don't matter. Hence:

```typescript
const hexValue = "0x00964d3b8ace15278dc0eac2077befee6906ac4e88f828ce9a549cc17ca3b816"; // note leading zeros
expect(BigNumber.from(hexValue).toHexString()).to.equal(hexValue);
```
```sh
AssertionError: expected '0x964d3b8ace15278dc0eac2077befee6906a…' to equal '0x00964d3b8ace15278dc0eac2077befee690…'
      + expected - actual

      -0x964d3b8ace15278dc0eac2077befee6906ac4e88f828ce9a549cc17ca3b816
      +0x00964d3b8ace15278dc0eac2077befee6906ac4e88f828ce9a549cc17ca3b81
```

You can verify this by seeing that the expected vs actual errors in comments above are the same minus the leading 2 zeroes after `0x`.

**Comment by jacque006** [comment]
### Solution

When comparing hexdecimal values in tests an other places, be sure to compare the **value** of the hexadecimal string rather than the hex string itself, such as with `BigNumber.eq`.

### Implications

We use `BigNumber.toHexString` in many, many places our code, including in operations where hexideximal string values are manipulated via string slicing/splicing/etc. We may have hidden bugs & other defects due to this.

@jzaki @voltrevo do you think this is a problem we need to address across our codebase in addition to this specific test?

**Comment by voltrevo** [comment]
@jacque006 Nice analysis! I've been wondering what those intermittent failures were... never noticed the difference was only in the leading zeros 😅.

> do you think this is a problem we need to address across our codebase in addition to this specific test?

Not super concerned, but definitely worth a look 👍.
